### ISSUE TITLE
Make README more clear that bundler is a Ruby gem

### ISSUE THREAD

**Issue by hoxxep** [sondr3/generator-jekyllized#116]
Yeoman was giving me a child process error after selecting the blog URL type. 

I looked at the install dependencies to troubleshoot and I couldn't find a node bundler package; had to deduce that it was a ruby gem. If the respective GitHub repos/homepages were linked that might help? Another option is specifying a list of terminal commands to run to install the node and ruby libraries.

Installed fine once I had bundler though, cheers for the great work!

**Comment by sondr3** [comment]
I'll just make the dependencies into URLs to their homepages, however, when it says it's a dependency it means it should be installed before running/installing this generator, so I figured it'd be a safe assumption that you'd know whether you had them installed or not :smile:. I used to have a pre-install hook that would look for the dependencies that I might add again since this seems to confuse people.

**Comment by hoxxep** [comment]
Yeah, I didn't look at the dependencies when I installed and assumed it would work, and the error message just mentioned the child process failed rather than explaining what was missing (which led to 10+ different attempts through the yeoman configurator). A pre-install check (or pre-run check; or an extra message on errors starting a child process) would be useful :+1: 

Also: the getting started guide inside the template could include the requirements needed for the gulp/jekyll setup; since other developer's might need to join the project having not used/known about the yeoman generator.

I botch-added the following under a "dependencies" header to our generated `README.md` after my colleague cloned the repo and had some issues.
```sh
cd <project-root>

# install ruby/jekyll dependencies
sudo gem install jekyll bundler
bundle install

# install npm/node dependencies
npm install -g gulpjs/gulp-cli#4.0
npm install
```

If you guys want to add some dependencies yourselves (since you'll know better what format you want the README to be in) that'd be sweet. Otherwise I can submit a PR tomorrow in a consistent format? :smile:

**Comment by sondr3** [comment]
I hadn't thought about how it would work when cloning since the generator installs all the dependencies automatically when you run it via Yeoman. I'll add a pre-install check to the generator, and might just update the generated REAMDE as well. I'll think about it. But feel free to shoot a PM and I will definitely take a look at it :smiley:
