### ISSUE TITLE
Could you consider adding browserify support ?

### ISSUE THREAD

**Issue by acezard** [sondr3/generator-jekyllized#154]
Very good jekyll stack but my only inconvenience is the absence of browserify, especially having babel support (es6 import syntax) it seems strange to just concat the js files instead of bundling them.

**Comment by sondr3** [comment]
Hey, sorry for the slow reply, busy with school. But yes, I probably could. I'd have to look into it though, I haven't used Browserify or any of the other similar packages. If you have any pointers I'd love to see them. :smile:

**Comment by papaponmx** [comment]
I think webpack would be a better option.

**Comment by sondr3** [comment]
As far as I know, moving to using webpack would require a substantial rewrite of the whole project, which might be something I do when/if it reaches v2. Right now I'm more or less just waiting for Gulp4 to be released so that I can finally release it properly, haha, they are taking their sweet time.

**Comment by sondr3** [comment]
I've been looking into this now that I finally have some time and I really cannot wrap my head around how to configure webpack or browserify, especially since it's not something that I would ever use. I just create small scripts that run on my webpages, not serious web apps that requires tree shaking and bundling, so I'm at a bit of a loss as to how I would approach this. Would love if you had any input on this.

**Comment by acezard** [comment]
Sorry, didn't reply last time. I think browserify would probably be more suited than webpack here (it's simpler). I could look into it. The "only" benefit would be to write client javascript with ES6 + allowing ES6 modules. It would be a simple gulp task really, I can look into doing a PR

**Comment by sondr3** [comment]
Sweet, that'd be great.

**Comment by sondr3** [comment]
I've managed to create a working gulp + webpack workflow now, I'll keep hitting away at it. Thanks for the offer though.
