### ISSUE TITLE
Build not copying CSS to `site` folder.

### ISSUE THREAD

**Issue by ColeTownsend** [sondr3/generator-jekyllized#74]
[Repo in question](https://github.com/ColeTownsend/coletownsend.com)

In the above repo, I haven't changed really any of the settings. It's not copying the css into the site directory after it runs `html`l nor `publish`.

**Comment by sondr3** [comment]
Oh gee, yeah, there's a typo in the gulpfile. Thanks for spotting. If you change [line 68 of the gulpfile to be](https://github.com/ColeTownsend/coletownsend.com/blob/master/gulpfile.js#L68): ` .pipe(gulp.dest("site/assets/stylesheets/"))` it should work. It's outputting to the wrong folder. I'll push a fix to the master branch, although I'm pretty much just waiting for Gulp to release their 4.0 version to release a new version right now :) Thanks for the report.

**Comment by sondr3** [comment]
Or, wait, uh, it's been a while since I looked at the code from the master branch, give me a second to check this out.

**Comment by ColeTownsend** [comment]
Sweet! Thanks for the speedy turnaround!


— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco

**Comment by sondr3** [comment]
Strange, just did a clean install locally from the master branch and it did copy over a minified stylesheet into the `site/assets/stylesheets` folder and linked it correctly in the header of the Jekyll site. It doesn't copy anything over at all into the folder for you?

**Comment by ColeTownsend** [comment]
nope! 


— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco

**Comment by ColeTownsend** [comment]
only with that updated line did it work.


— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco

**Comment by sondr3** [comment]
I think it might actually be because you removed the useref CSS reference from your `_includes/_head.html`. The `html` task looks for useref references in your HTML and works around that which would be why it's not moving the CSS. So you could either add some useref references to your HTML or just add a extra line to the `styles` task where you output your CSS to both your `serve` and `site` folder (because if you just changed the line as I said it'll change outputting to the `serve` folder).

**Comment by sondr3** [comment]
Which means that it won't move around your javascript files either unless you update the javascript task too to change where it moves your JS files to :)

**Comment by ColeTownsend** [comment]
What does that users thing look like?

**Comment by sondr3** [comment]
This is how it'd looks in the default template included:

```
<!-- CSS -->
<!-- build:css /assets/stylesheets/style.min.css -->
<link rel="stylesheet" href="/assets/stylesheets/style.css">
<!-- endbuild -->
```
Not really sure how it would work with the `data-no-instant` thing in your CSS tag either, but if you want your CSS and to be moved to the `site` folder and minimized you need these useref references because that's how the `html` task works.

**Comment by ColeTownsend** [comment]
Got it! I'm testing meow.



— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco
